'use strict';(function(window){var nextId=0;window.BrowserFrame=function BrowserFrame(){this.element=null;this._id=nextId++;createFrame.apply(this,arguments);Object.defineProperty(this,'focusElement',{get(){return this.element&&this.element.querySelector('browser');}});return this;};BrowserFrame.prototype.CLASS_NAME='browser';function createFrame(config,frame){var browser=frame||config.frame||document.createElement('web-view');browser.setAttribute('timestamp',config.timestamp||Date.now());browser.name=config.window_name||'main';browser.openWindowInfo=config.openWindowInfo||null;if(config.manifest?.b2g_features?.userAgentInfo){browser.userAgentExtensions=config.manifest.b2g_features.userAgentInfo;}
if(config.oop){browser.setAttribute('remote','true');window.dispatchEvent(new CustomEvent('launch-preallocated-process'));}
if(config.manifestUrl){browser.setAttribute('mozapp',config.manifestUrl);}
if(config.isInputMethod){browser.setAttribute('ignoreuserfocus','true');}
setMozAppType(browser,config);if(config.url){browser.src=config.url;browser.dataset.url=config.url;}
browser.id=this.CLASS_NAME+this._id;browser.classList.add(this.CLASS_NAME);this.config=config;this.element=browser;}
function setMozAppType(iframe,config){if(config.url.startsWith(window.location.protocol+'//callscreen.gaiamobile.org')||config.url.startsWith(window.location.protocol+'//clock.gaiamobile.org')){iframe.setAttribute('mozapptype','critical');}else if(config.url.startsWith(window.location.protocol)&&config.manifest&&'high'===config.manifest.priority){iframe.setAttribute('mozapptype','hipri');}else if(config.isHomescreen){iframe.setAttribute('mozapptype','homescreen');iframe.setAttribute('transparent','true');}else if(config.isSearch){iframe.setAttribute('mozapptype','search');}else if(config.isInputMethod){iframe.setAttribute('mozapptype','inputmethod');}}}(this));function killCorruptTopMostWindow(element){var topMostWindow=Service.query('getTopMostWindow');if(topMostWindow&&(topMostWindow.browser.element===element)){topMostWindow.kill();}}
function getBrowserProperty(element,name){var result=false;if(element){try{result=element[name];}catch(e){console.error(e);killCorruptTopMostWindow(element);result=false;}}
return result;}
function setBrowserProperty(element,name,option){if(element){try{element[name]=option;}catch(e){console.error(e);killCorruptTopMostWindow(element);}}}