'use strict';

(function (exports) {
  /**
   * The errno values with four digits are defined by kaicloud api doc.
   **/
  const KaiAccountErrorTable = {
    // 1xxx: General errors
    1001: 'MISSING_ID_IN_URL',
    1002: 'EMPTY_PAYLOAD',
    1003: 'PAYLOAD_CANNOT_BE_UNMARSHALLED',
    1004: 'JWT_CANNOT_BE_RECOVERED',
    1005: 'FAILED_TO_ATTACH_DATA_TO_REQUEST',
    1006: 'FAILED_TO_ATTACH_DATA_TO_RESPONSE',
    1007: 'FAILED_TO_DETACH_DATA_FROM_REQUEST',
    1008: 'FAILED_TO_DETACH_DATA_FROM_RESPONSE',
    1009: 'NATS_COMMUNICATION_FAILED',
    1010: 'JWT_BLACKLISTED',
    1011: 'DL_SUBSYSTEM_FAILED',
    1012: 'NOT_PROPERLY_INITIALIZED',

    // 2xxx: Account specific errors
    2001: 'WRONG_ACCOUNT_ID_FORMAT',
    2002: 'WRONG_FIRST_NAME_FORMAT',
    2003: 'WRONG_LAST_NAME_FORMAT',
    2004: 'WRONG_BIRTHDAY_FORMAT',
    2005: 'WRONG_GENDER_FORMAT',
    2006: 'WRONG_EMAIL_FORMAT',
    2007: 'MISSING_PASSWORD_FIELD',
    2008: 'DUPLICATED_EMAIL_VALUE',
    2009: 'WRONG_PHONE_FORMAT',
    2010: 'MISSING_PHONE_PASSWORD_FIELD',
    2011: 'WRONG_SECOND_PHONE_FORMAT',
    2012: 'MISSING_AT_LEAST_ONE_CONTACT_FIELD',
    2013: 'DUPLICATED_EMAIL_VALUE',
    2014: 'DUPLICATED_PHONE_VALUE',
    2015: 'NOT_OWNER',
    2016: 'NOT_PARTNER',
    2017: 'NOT_ROOT',
    2018: 'FAILED_TO_UNMARSHAL_DL_RECORD',
    2019: 'WRONG_USER_IDENTITY',
    2020: 'TOO_MANY_CONTACT_INFO_UPDATED',
    2021: 'PHONE_UPDATE_LEADS_TO_INVALID_ACCOUNT',
    2022: 'EMAIL_UPDATE_LEADS_TO_INVALID_ACCOUNT',
    2023: 'DUPLICATE_ACCOUNT_WITH_PHONE',
    2024: 'DUPLICATE_ACCOUNT_WITH_EMAIL',
    2025: 'FAILED_TO_RETRIEVE_ACCOUNT_FROM_DB',
    2026: 'FAILED_TO_SAVE_ACCOUNT_TO_DB',
    2027: 'FAILED_TO_RETRIEVE_ACCOUNT_FROM_EPHEM_DB',
    2028: 'FAILED_TO_SAVE_ACCOUNT_TO_EPHEM_DB',
    2029: 'FAILED_TO_MARSHAL_RECORD',
    2030: 'DUPLICATE_ACCOUNT_WITH_LOGIN',
    2031: 'DUPLICATE_ACCOUNT_WITH_ID',
    2032: 'DUPLICATE_ACCOUNT',
    2033: 'FAILED_TO_MARSHAL_ACCOUNT',
    2034: 'PENDING_ACTIVATION_MODULE_FAILED',
    2035: 'UNVERIFIED_CONTACT_MODULE_FAILED',
    2036: 'ACCOUNT_MISSING_PARAMETER',
    2037: 'ACCOUNT_BAD_FORMATTED_PARAMETER',
    2038: 'ACCOUNT_BAD_EPHEMERAL_PARAMETER_VALUE',
    2039: 'EPHEMERAL_ACCOUNT_NOT_FOUND',
    2040: 'ACCOUNT_NOT_FOUND',
    2041: 'INVALID_ACCOUNT_CONTACT_PARAMETER',
    2042: 'EPHEMERAL_ACCOUNT_LIKELY_EXPIRED',
    2043: 'MISSING_MANDATORY_EMAIL_FIELD',
    2044: 'NO_ACCOUNT_BOUND_WITH_CONTACT_FOUND',
    2045: 'WRONG_LANGUAGE_FORMAT',

    // 3xxx: OAuth2 Specific error
    3001: 'FAILED_TO_READ_PUBLIC_KEY',
    3002: 'FAILED_TO_READ_PRIVATE_KEY',
    3003: 'FAILED_TO_MARSHAL_CLAIMS',
    3004: 'FAILED_TO_UNMARSHAL_CLAIMS',
    3005: 'FAILED_TO_MARSHAL_LOGIN_REQ',
    3006: 'FAILED_TO_UNMARSHAL_LOGIN_RSP',
    3007: 'FAILED_TO_MARSHAL_ACCESS_TOKEN',
    3008: 'FAILED_TO_UNMARSHAL_ACCESS_TOKEN',
    3009: 'FAILED_TO_EXTRACT_CLAIMS',
    3010: 'FAILED_TO_PARSE_CLAIMS',
    3011: 'MISSING_FIELDS_IN_CLAIMS',
    3012: 'AUDIENCE_MISMATCH',
    3013: 'JWT_IS_NOT_A_REFRESH_TOKEN',
    3014: 'REFRESH_TOKEN_EXPIRED_OR_NOT_REGISTERED',
    3015: 'FAILED_TO_INVALIDATE_HAWK_KEY',
    3016: 'FAILED_TO_UNREGISTER_REFRESH_TOKEN',
    3017: 'FAILED_TO_INVALIDATE_SESSION',

    // 4xxx: JWT Specific error
    4001: 'FAILED_TO_PARSE_JWT',
    4002: 'FAILED_TO_VERIFY_SIGNATURE'
  };

  exports.KaiAccountErrorTable = KaiAccountErrorTable;
}(window));
