'use strict';(function(exports){var _id=0;var AppChrome=function AppChrome(app){this.app=app;this.instanceID=_id++;this.containerElement=app.element;this._recentTitle=false;this._titleTimeout=null;this.scrollable=app.browserContainer;this.render();if(!this.app.isBrowser()&&this.app.name){this._gotName=true;this.setFreshTitle(this.app.name);}
this.reConfig();};AppChrome.prototype=Object.create(window.BaseUI.prototype);AppChrome.prototype.CLASS_NAME='AppChrome';AppChrome.prototype.EVENT_PREFIX='chrome';AppChrome.prototype.FRESH_TITLE=500;AppChrome.prototype.LOCATION_COALESCE=250;AppChrome.prototype._DEBUG=false;AppChrome.prototype.destroy=function(){if(this.browserWindowNavigator){this.browserWindowNavigator.destroy();this.browserWindowNavigator=undefined;}
BaseUI.prototype.destroy.call(this);}
AppChrome.prototype.reConfig=function(){var chrome=this.app.config.chrome;if(!chrome){return;}
if(this.isSearchApp()){this.app.element.classList.add('search-app');}else{this.app.element.classList.remove('search-app');}
if(chrome.bar){this.app.element.classList.add('bar');this.bar.classList.add('visible');}
if(chrome.scrollable){this.app.element.classList.add('collapsible');this.scrollable.scrollgrab=true;}
if(chrome.maximized){this.element.classList.add('maximized');if(!this.app.isBrowser()){this.app.element.classList.add('scrollable');}}
if(!this.app.isPopupWindow()&&(this.app.isBrowserOrSearch()||this.app.isCursorEnabled())){if(this.browserWindowNavigator){this.browserWindowNavigator.destroy();}
this.browserWindowNavigator=new BrowserWindowNavigator(this);}};AppChrome.prototype.combinedView=function an_combinedView(){var className=this.CLASS_NAME+this.instanceID;return`<div class="chrome chrome-combined" id="${className}">
              <gaia-progress class="hidden"></gaia-progress>
              <div class="controls">
                <div class="urlbar js-chrome-ssl-information">
                  <div class="chrome-ssl-indicator chrome-title-container">
                    <span data-icon="lock" class="hide"></span>
                    <span class="title p-pri" dir="auto"></span>
                  </div>
                </div>
              </div>
              <div class="invisible"></div>
            </div>`;};AppChrome.prototype.view=function an_view(){var className=this.CLASS_NAME+this.instanceID;return`<div class="chrome chrome-plain" id="${className}">
            <gaia-progress class="hidden"></gaia-progress>
            <section role="region" class="bar">
              <gaia-header class='js-chrome-ssl-information' compact="true">
                <div slot="text" class="chrome-ssl-indicator chrome-ssl-indicator-ltr">
                  <span data-icon="lock" class="hide"></span>
                </div>
                <h1 slot="text" class="chrome-title-container">
                  <bdi dir="auto" class="title p-pri"></bdi>
                </h1>
                <div slot="text" class="chrome-ssl-indicator chrome-ssl-indicator-rtl">
                </div>
              </gaia-header>
            </section>
            <div class="invisible" style="display:none;"></div>
          </div>`;};AppChrome.prototype.__defineGetter__('height',function ac_getHeight(){if(this._height){return this._height;}
this._height=this.element.getBoundingClientRect().height;return this._height;});AppChrome.prototype._fetchElements=function ac__fetchElements(){this.element=this.containerElement.querySelector('.chrome');this.progress=this.element.querySelector('gaia-progress');this.title=this.element.querySelector('.chrome-title-container > .title');this.sslIndicator=this.element.querySelector('.js-chrome-ssl-information');this.sslDataIcon=this.element.querySelector('.js-chrome-ssl-information  > span[data-icon]');this.bar=this.element.querySelector('.bar');this.invisible=this.element.querySelector('.invisible');};AppChrome.prototype.handleEvent=function ac_handleEvent(evt){switch(evt.type){case'scroll':this.handleScrollEvent(evt);break;case'_loading':this.show(this.progress);this.progress.classList.remove('hidden');if(!this.isSearchApp()&&this.title.textContent===''){this.updateLoadingLocation(this.app.browser.element.src);}
break;case'_loaded':this.hide(this.progress);this.progress.classList.add('hidden');break;case'loadstart':this.handleLoadStart(evt);break;case'loadend':this.handleLoadEnd(evt);break;case'error':this.handleError(evt);break;case'locationchange':this.handleLocationChanged(evt);break;case'scrollareachanged':this.handleScrollAreaChanged(evt);break;case'_securitychange':this.handleSecurityChanged(evt);break;case'titlechange':this.handleTitleChanged(evt);break;case'metachange':this.handleMetaChange(evt);break;case'_namechanged':this.handleNameChanged(evt);break;}};AppChrome.prototype.handleKey=function(key){if(!this.app.isPopupWindow()&&(this.app.isBrowserOrSearch()||this.app.isCursorEnabled())){return this.browserWindowNavigator.handleKey(key);}
return false;};AppChrome.prototype.handleScrollEvent=function ac_handleScrollEvent(){if(!this.containerElement.classList.contains('scrollable')){return;}
var element=this.element;if(this.scrollable.scrollTop>=this.scrollable.scrollTopMax-1){element.classList.remove('maximized');}else{element.classList.add('maximized');}
if(this.app.isActive()){this.app.publish('titlestatechanged');}};AppChrome.prototype._registerEvents=function ac__registerEvents(){if(this.useCombinedChrome()){this.scrollable.addEventListener('scroll',this);}
this.app.element.addEventListener('loadstart',this);this.app.element.addEventListener('loadend',this);this.app.element.addEventListener('error',this);this.app.element.addEventListener('locationchange',this);this.app.element.addEventListener('titlechange',this);this.app.element.addEventListener('metachange',this);this.app.element.addEventListener('scrollareachanged',this);this.app.element.addEventListener('_securitychange',this);this.app.element.addEventListener('_loading',this);this.app.element.addEventListener('_loaded',this);this.app.element.addEventListener('_namechanged',this);var element=this.element;var animEnd=function(evt){if(evt&&evt.target!==element){return;}
var publishEvent=this.isMaximized()?'expanded':'collapsed';this.app.publish('chrome'+publishEvent);}.bind(this);element.addEventListener('transitionend',animEnd);};AppChrome.prototype._unregisterEvents=function ac__unregisterEvents(){if(this.useCombinedChrome()){this.scrollable.removeEventListener('scroll',this);}
if(!this.app){return;}
this.app.element.removeEventListener('loadstart',this);this.app.element.removeEventListener('loadend',this);this.app.element.removeEventListener('error',this);this.app.element.removeEventListener('locationchange',this);this.app.element.removeEventListener('titlechange',this);this.app.element.removeEventListener('metachange',this);this.app.element.removeEventListener('scrollareachanged',this);this.app.element.removeEventListener('_securitychange',this);this.app.element.removeEventListener('_loading',this);this.app.element.removeEventListener('_loaded',this);this.app.element.removeEventListener('_namechanged',this);this.app=null;};AppChrome.prototype.handleNameChanged=function ac_handleNameChanged(){this._title=this.app.name;this._gotName=true;};AppChrome.prototype.setFreshTitle=function ac_setFreshTitle(title){if(this.isSearchApp()){return;}
this._title=this.title.textContent=title;clearTimeout(this._titleTimeout);this._recentTitle=true;this._titleTimeout=setTimeout((function(){this._recentTitle=false;}).bind(this),this.FRESH_TITLE);};AppChrome.prototype.handleScrollAreaChanged=function(evt){if(this.containerElement.classList.contains('scrollable')){return;}
if(evt.detail.height>=this.containerElement.clientHeight){this.containerElement.classList.add('scrollable');}};AppChrome.prototype.handleSecurityChanged=function(){var sslState=this.app.getSSLState();this.sslIndicator.dataset.ssl=sslState;this.sslIndicator.classList.toggle('chrome-has-ssl-indicator',sslState==='broken'||sslState==='secure');if(!this.sslDataIcon){return;}
if(sslState==='broken'){this.sslDataIcon.setAttribute('data-icon','lock-broken');}else if(sslState==='secure'){this.sslDataIcon.setAttribute('data-icon','lock');}else{this.sslDataIcon.setAttribute('data-icon','');}};AppChrome.prototype.handleTitleChanged=function(evt){if(this._gotName||this._fixedTitle){return;}
this.setFreshTitle(evt.detail.title||this._currentURL);this._titleChanged=true;};AppChrome.prototype.handleMetaChange=function ac__handleMetaChange(evt){var detail=evt.detail;if(detail.name!=='theme-color'||!detail.type){return;}
var color='';if(detail.type!=='removed'){color=detail.content;}
this.setThemeColor(color);};AppChrome.prototype.setThemeColor=function ac_setThemColor(color){var bottomApp=this.app.getBottomMostWindow();if(this.app.CLASS_NAME==='PopupWindow'&&bottomApp&&bottomApp.themeColor){color=bottomApp.themeColor;}
this.app.themeColor=color;this.element.style.backgroundColor=color;this.invisible.style.backgroundColor=color;if(this.app.isPWA()){this.app.element.classList.add('hosted');if(this.app.isProgressBarEnabled()){this.element.classList.add('progress-bar-enabled');}}
this.updateBackgroundBright();};AppChrome.prototype.updateBackgroundBright=function ac_updateBgBright(){if(!this.element)return;const invisibleBackgroundColor=window.getComputedStyle(this.invisible).getPropertyValue('background-color');const colorCodeRegex=/rgba*\((\d+), (\d+), (\d+)/;var colorCodes=colorCodeRegex.exec(invisibleBackgroundColor);if(!colorCodes||colorCodes.length===0){return;}
var brightness=0;if(colorCodes){var r=parseInt(colorCodes[1]);var g=parseInt(colorCodes[2]);var b=parseInt(colorCodes[3]);brightness=Math.sqrt((r*r)*0.241+(g*g)*0.691+(b*b)*0.068);}
this.app.element.classList.toggle('light',brightness>200);this.app.publish('titlestatechanged');};AppChrome.prototype.render=function(){this.publish('willrender');var view=this.useCombinedChrome()?this.combinedView():this.view();this.app.element.insertAdjacentHTML('afterbegin',view);this._fetchElements();this._registerEvents();this.publish('rendered');};AppChrome.prototype.useLightTheming=function ac_useLightTheming(){if(this.app.CLASS_NAME=='PopupWindow'&&this.app.rearWindow&&this.app.rearWindow.appChrome){return this.app.rearWindow.appChrome.useLightTheming();}
const classList=this.app.element.classList;return classList.contains('light');};AppChrome.prototype.useCombinedChrome=function ac_useCombinedChrome(){return this.app.config.chrome&&!this.app.config.chrome.bar;};AppChrome.prototype._updateLocation=function ac_updateTitle(title){if(this._titleChanged||this._gotName||this._recentTitle||this._fixedTitle){return;}
this._title=title;this.updateLoadingLocation(title);};AppChrome.prototype.handleLocationChanged=function ac_handleLocationChange(evt){if(!this.app){return;}
var anchorChange=false;if(this._currentURL&&evt.detail.url){anchorChange=this._currentURL.replace(/#.*/g,'')===evt.detail.url.replace(/#.*/g,'');}
setTimeout(this._updateLocation.bind(this,evt.detail.url),this.LOCATION_COALESCE);this._currentURL=evt.detail.url;if(!this.app.isBrowser()){return;}
this._gotName=false;if(!anchorChange){this.containerElement.classList.remove('scrollable');if(!this.isMaximized()){this.element.classList.add('maximized');}
this.scrollable.scrollTop=0;if(this.app.isBrowser()){this.setThemeColor('var(--color-gs00)');}}};AppChrome.prototype.updateLoadingLocation=function(url){if(url){const title=url.replace(/^(http|ftp|https):\/\//g,'');if(this.app&&this.app.loading||this.title.textContent!==title){this.title.textContent=title;}}};AppChrome.prototype.handleLoadStart=function ac_handleLoadStart(){this.containerElement.classList.add('loading');this._titleChanged=false;};AppChrome.prototype.handleLoadEnd=function ac_handleLoadEnd(){this.containerElement.classList.remove('loading');};AppChrome.prototype.handleError=function ac_handleError(evt){if(evt.detail&&evt.detail.type==='fatal'){return;}
if(this.useCombinedChrome()&&this.app.config.chrome.scrollable){this.element.classList.add('maximized');this.containerElement.classList.remove('scrollable');}};AppChrome.prototype.maximize=function ac_maximize(callback){var element=this.element;element.classList.add('maximized');if(!callback){return;}
eventSafety(element,'transitionend',callback,250);};AppChrome.prototype.isMaximized=function ac_isMaximized(){return this.element.classList.contains('maximized');};AppChrome.prototype.isSearch=function ac_isSearch(){var dataset=this.app.config;return dataset.searchURL&&this._currentURL===dataset.searchURL;};AppChrome.prototype.isSearchApp=function(){return this.app.config.manifest?.role==='search';};AppChrome.prototype.hasNavigation=function ac_hasNavigation(){return this.app.isBrowser()||(this.app.config.chrome&&this.app.config.chrome.navigation);};AppChrome.prototype.addBookmark=function ac_addBookmark(){const dataset=this.app.config;const favicons=this.app.favicons;let name=this.isSearch()?dataset.searchName:this.title.textContent;const url=this._currentURL||dataset.url;const sharedOrigin=window.AppOrigin.getOrigin('shared');return LazyLoader.load(sharedOrigin+'/js/helper/common/icons_helper.js').then(()=>IconsHelper.getIcon(url,null,{icons:favicons})).then((icon)=>{const options={name:'bookmark',data:{action:'add',url:url,name:name,icon:icon}};return new WebActivity(options.name,options.data).start();}).catch(()=>Promise.reject('hasPinned'));};exports.AppChrome=AppChrome;}(window));